package common

// Variable names for FCGI_GET_VALUES / FCGI_GET_VALUES_RESULT records
const (
	FCGI_MAX_CONNS  = "FCGI_MAX_CONNS"
	FCGI_MAX_REQS   = "FCGI_MAX_REQS"
	FCGI_MPXS_CONNS = "FCGI_MPXS_CONNS"
)
